'use client'

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'en' | 'id'

interface Translations {
  [key: string]: string
}

const dictionaries: Record<Language, Translations> = {
  en: {
    // Navigation
    'Dashboard': 'Dashboard',
    'Beranda': 'Dashboard',
    'Akun Perkiraan': 'Chart of Accounts',
    'Penjualan': 'Sales',
    'Penawaran Penjualan': 'Sales Quote',
    'Uang Muka Penjualan': 'Sales Down Payment',
    'Faktur Penjualan': 'Sales Invoice',
    'Penerimaan Penjualan': 'Sales Receipt',
    'Pelanggan': 'Customers',
    'Pembelian': 'Purchases',
    'Pesanan Pembelian': 'Purchase Order',
    'Faktur Pembelian': 'Purchase Invoice',
    'Uang Muka Pembelian': 'Purchase Down Payment',
    'Pembayaran Pembelian': 'Purchase Payment',
    'Pemasok': 'Suppliers',
    'Barang & Jasa': 'Products & Services',
    'Buku Besar': 'General Ledger',
    'Karyawan': 'Employees',
    'Analytics': 'Analytics',
    'Orders': 'Orders',
    'Products': 'Products',
    'Customers': 'Customers',
    'File Manager': 'File Manager',
    'Chat': 'Chat',
    'Mail': 'Mail',
    'Kanban': 'Kanban',
    'Calendar': 'Calendar',
    'Project': 'Project',
    'Tasks': 'Tasks',
    'My Tasks': 'My Tasks',
    'AI Assistant': 'AI Assistant',
    'Layouts': 'Layouts',
    'Settings': 'Settings',
    'Workspace': 'Workspace',
    'Apps': 'Apps',
    'Search anything': 'Search anything...',
    'Developer': 'Developer',
    'Setup Project': 'Setup Project',
    'Milestones': 'Milestones',
    'Module Flows': 'Module Flows',
    'Administration': 'Administration',
    'Roles & Permissions': 'Roles & Permissions',
    'Finance': 'Finance',
    'HR': 'HR',
    // Settings page
    'Localization': 'Localization',
    'Manage your timezone and language preferences.': 'Manage your timezone and language preferences.',
    'Language': 'Language',
    'Timezone': 'Timezone',
    'Date Format': 'Date Format',
    'Save preferences': 'Save preferences',
    'Save changes': 'Save changes',
    'Preferences saved': 'Preferences saved!',
    // Common UI
    'Loading': 'Loading...',
    'Search': 'Search',
    'Add': 'Add',
    'Edit': 'Edit',
    'Delete': 'Delete',
    'Cancel': 'Cancel',
    'Confirm': 'Confirm',
    'Export': 'Export',
    'Import': 'Import',
    'Status': 'Status',
    'Name': 'Name',
    'Email': 'Email',
    'Role': 'Role',
    'Department': 'Department',
    'Actions': 'Actions',
    'Total': 'Total',
    'Date': 'Date',
    'Description': 'Description',
    'Amount': 'Amount',
    'Period': 'Period',
    'No data found': 'No data found.',
    'Paid': 'Paid',
    'Pending': 'Pending',
    'Approve': 'Approve',
    'Reject': 'Reject',
    'approved': 'approved',
    'rejected': 'rejected',
    'Leave Type': 'Leave Type',
    'Duration': 'Duration',
    'Reason': 'Reason',
    'Candidate': 'Candidate',
    'Role Applied': 'Role Applied',
    'Applied Date': 'Applied Date',
    'Rating': 'Rating',
    'View Profile': 'View Profile',
    'Payroll generated successfully!': 'Payroll generated successfully!',
    'Payroll data exported successfully!': 'Payroll data exported successfully!',
    'Failed to export payroll data.': 'Failed to export payroll data.',
    'Employee updated successfully!': 'Employee updated successfully!',
    'Employee list is sourced from the Users database.': 'Employee list is sourced from the Users database.',
    'View your organization\'s members. To add or remove users, use User Management.': 'View your organization\'s members. To add or remove users, use User Management.',
    'Manage employee leave requests and attendance records.': 'Manage employee leave requests and attendance records.',
    'View and manage employee salaries, allowances, and deductions.': 'View and manage employee salaries, allowances, and deductions.',
    'Applicant Tracking System to manage active job applications.': 'Applicant Tracking System to manage active job applications.',
    'Are you sure you want to update this leave request?': 'Are you sure you want to update this leave request?',
    // Dashboard
    'Welcome back': 'Welcome back',
    'Total Revenue': 'Total Revenue',
    'Active Users': 'Active Users',
    'New Orders': 'New Orders',
    'Growth': 'Growth',
    // HR
    'Employees': 'Employees',
    'Attendance': 'Attendance',
    'Payroll': 'Payroll',
    'Recruitment': 'Recruitment',
    'HR Overview': 'HR Overview',
    'Leave Requests': 'Leave Requests',
    'Total Employees': 'Total Employees',
    'Interviews': 'Interviews',
    'Departments': 'Departments',
    'Generate Payroll': 'Generate Payroll',
    'Net Pay': 'Net Pay',
    'Basic Salary': 'Basic Salary',
    'Allowance': 'Allowance',
    'Deduction': 'Deduction',
    'Finance Overview': 'Finance Overview',
    'Monitor your key financial metrics and recent activities.': 'Monitor your key financial metrics and recent activities.',
    'Total Revenue': 'Total Revenue',
    'Total Expenses': 'Total Expenses',
    'Net Profit': 'Net Profit',
    'Outstanding Invoices': 'Outstanding Invoices',
    'Cash & Bank': 'Cash & Bank',
    'Recent Transactions': 'Recent Transactions',
    'Reference': 'Reference',
    'Type': 'Type',
    'Account': 'Account',
    'Edit Employee': 'Edit Employee',
    'Add New Employee': 'Add New Employee',
    'Update employee details here.': 'Update employee details here.',
    'Enter the details of the new employee.': 'Enter the details of the new employee.',
    'Select Employee': 'Select Employee',
    'Create a new payroll record for an employee.': 'Create a new payroll record for an employee.',
    'A quick glance at human resources statistics and activities.': 'A quick glance at human resources statistics and activities.',
    'Employee Distribution': 'Employee Distribution',
    'Headcount by department': 'Headcount by department',
    'Hiring Trends': 'Hiring Trends',
    'New hires over the last 6 months': 'New hires over the last 6 months',
    'Recent Leave Requests': 'Recent Leave Requests',
    'Upcoming Interviews': 'Upcoming Interviews',
    'active': 'active',
    'pending approval': 'pending approval',
    'Across the organization': 'Across the organization',
    'upcoming sessions': 'upcoming sessions',
    'Record Income': 'Record Income',
    'Add Expense': 'Add Expense',
    'Add Transaction': 'Add Transaction',
    'Create Invoice': 'Create Invoice',
    'Vendor': 'Vendor',
    'Category': 'Category',
    'Invoice No.': 'Invoice No.',
    'Customer': 'Customer',
    'Due Date': 'Due Date',
    'Income': 'Income',
    'Save': 'Save',
    'Add': 'Add',
    'New Data': 'New Data',
    'Filter': 'Filter',
    'From': 'From',
    'To': 'To',
    'Date': 'Date',
    'Description': 'Description',
    'Total': 'Total',
    'Status': 'Status',
    'Action': 'Action',
    'Name': 'Name',
    'Code': 'Code',
    'Type': 'Type',
    'Unit': 'Unit',
    'Customer': 'Customer',
    'Supplier': 'Supplier',
    'Number': 'Number',
    'Debit': 'Debit',
    'Credit': 'Credit',
    'Ending Balance': 'Ending Balance',
    'Transaction Type': 'Transaction Type',
    'Other Information': 'Other Information',
    'Chart of Accounts': 'Chart of Accounts',
    'General Ledger': 'General Ledger',
    'Products & Services': 'Products & Services',
    'Sales Quote': 'Sales Quote',
    'Sales Invoice': 'Sales Invoice',
    'Sales Down Payment': 'Sales Down Payment',
    'Sales Receipt': 'Sales Receipt',
    'Purchase Order': 'Purchase Order',
    'Purchase Invoice': 'Purchase Invoice',
    'Purchase Down Payment': 'Purchase Down Payment',
    'Purchase Payment': 'Purchase Payment',
    'Brand': 'Brand',
    'Income & Expenses': 'Income & Expenses',
    'Total Balance': 'Total Balance',
    'Unpaid Invoices': 'Unpaid Invoices',
    'Total Transactions': 'Total Transactions',
    'Unpaid': 'Unpaid',
    'Expense': 'Expense',
    'Transfer': 'Transfer',
    'Transactions': 'Transactions',
    'Invoices': 'Invoices',
    'Expenses': 'Expenses',
    'Accounts': 'Accounts',
    'Income': 'Income',
    'Balance': 'Balance',
    'All Categories': 'All Categories',
    'Delete Expense': 'Delete Expense',
    'Delete Transaction': 'Delete Transaction',
    'Delete Invoice': 'Delete Invoice',
    'Are you sure you want to delete this expense record? This action cannot be undone.': 'Are you sure? This cannot be undone.',
    'Are you sure you want to delete this record? This action cannot be undone.': 'Are you sure? This cannot be undone.',
    'Track and analyze your company spending.': 'Track and analyze your company spending.',
    'Track and manage your company invoices.': 'Track and manage your company invoices.',
    'Manage your bank and cash accounts.': 'Manage your bank and cash accounts.',
    'Export': 'Export',
    'Last 30 days': 'Last 30 days',
    'Last 7 days': 'Last 7 days',
    'This year': 'This year',
    'vs. last month': 'vs. last month',
    'Avg. order value': 'Avg. order value',
    'Conversion rate': 'Conversion rate',
    'Revenue overview': 'Revenue overview',
    'Monthly revenue performance': 'Monthly revenue performance',
    'Traffic sources': 'Traffic sources',
    'Where your visitors come from': 'Where your visitors come from',
    'Direct': 'Direct',
    'Organic search': 'Organic search',
    'Social media': 'Social media',
    'Other': 'Other',
    'Recent activity': 'Recent activity',
    'View all': 'View all',
    'Monthly goals': 'Monthly goals',
    'Keep the momentum going': 'Keep the momentum going',
    'Revenue target': 'Revenue target',
    'New customers': 'New customers',
    'Orders fulfilled': 'Orders fulfilled',
    'Top products': 'Top products',
    'Recent orders': 'Recent orders',
    'Your latest transactions': 'Your latest transactions',
    'Order': 'Order',
    'Date': 'Date',
    'Amount': 'Amount',
    'Status': 'Status',
    'Analytics overview': 'Analytics overview',
    'A clear view of the signals shaping your business this month.': 'A clear view of the signals shaping your business this month.',
    'Export report': 'Export report',
    'Unique visitors': 'Unique visitors',
    'Page views': 'Page views',
    'vs last month': 'vs last month',
    'Acquisition performance': 'Acquisition performance',
    'Visitors and conversions over the selected period': 'Visitors and conversions over the selected period',
    'Visitors': 'Visitors',
    'Conversions': 'Conversions',
    'Share of total visitors': 'Share of total visitors',
    'total visitors': 'total visitors',
    'Conversion funnel': 'Conversion funnel',
    'How visitors move through your store': 'How visitors move through your store',
    'Details': 'Details',
    'Visited site': 'Visited site',
    'Viewed product': 'Viewed product',
    'Added to cart': 'Added to cart',
    'Completed checkout': 'Completed checkout',
    'Top pages': 'Top pages',
    'Most visited this month': 'Most visited this month',
    'Revenue by channel': 'Revenue by channel',
    'Attributed revenue for the last 30 days': 'Attributed revenue for the last 30 days',
    'Referral': 'Referral',
    'Workspace details and timezone': 'Workspace details and timezone',
    'Profile and login credentials': 'Profile and login credentials',
    'Theme and UI preferences': 'Theme and UI preferences',
    'Email and push alerts': 'Email and push alerts',
    '2FA and active sessions': '2FA and active sessions',
    'Payment methods and plans': 'Payment methods and plans',
    'Workspace Profile': 'Workspace Profile',
    "This is your company's presence on HaiMotion.": "This is your company's presence on HaiMotion.",
    'Workspace Logo': 'Workspace Logo',
    'JPG, GIF or PNG. Max size 2MB.': 'JPG, GIF or PNG. Max size 2MB.',
    'Workspace Name': 'Workspace Name',
    'Workspace URL': 'Workspace URL',
    'Save changes': 'Save changes',
    'Preferences saved': 'Preferences saved',
    'Theme Preferences': 'Theme Preferences',
    'Customize the look and feel of your dashboard.': 'Customize the look and feel of your dashboard.',
    'Interface Theme': 'Interface Theme',
    'Light': 'Light',
    'Dark': 'Dark',
    'System': 'System',
    'Accent Color': 'Accent Color',
    'Security Settings': 'Security Settings',
    'Manage your authentication methods and passkeys.': 'Manage your authentication methods and passkeys.',
    'Passkeys (WebAuthn)': 'Passkeys (WebAuthn)',
    'Please enter a device name.': 'Please enter a device name.',
    'Failed to add passkey': 'Failed to add passkey',
    'Network error or cancelled.': 'Network error or cancelled.',
    'Loading passkeys...': 'Loading passkeys...',
    'No passkeys registered yet.': 'No passkeys registered yet.',
    'Unknown Device': 'Unknown Device',
    'Added: ': 'Added: ',
    'Unknown': 'Unknown',
    'Add New Passkey (e.g. My MacBook)': 'Add New Passkey (e.g. My MacBook)',
    'Device Name': 'Device Name',
    'Add Passkey': 'Add Passkey',
    'Adding...': 'Adding...',
    'Profile saved successfully!': 'Profile saved successfully!',
    'Passwords do not match!': 'Passwords do not match!',
    'Basic Information': 'Basic Information',
    'Your name, staff code, and a short bio.': 'Your name, staff code, and a short bio.',
    'Position / Title': 'Position / Title',
    'Managed by admin': 'Managed by admin',
    'Staff Code': 'Staff Code',
    'Bio': 'Bio',
    'Tell us a little about yourself...': 'Tell us a little about yourself...',
    'Account & Security': 'Account & Security',
    'Role, login email, and account password.': 'Role, login email, and account password.',
    'User Role': 'User Role',
    'Role is managed by admin': 'Role is managed by admin',
    'Email Login': 'Email Login',
    'Optional — for Gmail notifications': 'Optional — for Gmail notifications',
    "Leave blank if you don't want to change your password": "Leave blank if you don't want to change your password",
    'Confirm Password': 'Confirm Password',
    'Passwords do not match': 'Passwords do not match',
    'Passwords match': 'Passwords match',
    'Profile Picture': 'Profile Picture',
    'Upload and adjust your avatar photo.': 'Upload and adjust your avatar photo.',
    'Uploading...': 'Uploading...',
    'Upload new photo': 'Upload new photo',
    'Remove': 'Remove',
    'JPG, GIF or PNG. Max 5MB. Hover the photo to upload directly.': 'JPG, GIF or PNG. Max 5MB. Hover the photo to upload directly.',
    'Fields marked with': 'Fields marked with',
    'are required.': 'are required.',
    'Saving...': 'Saving...',
    'Save Changes': 'Save Changes',
    'Daily Attendance': 'Daily Attendance',
    'Import Excel': 'Import Excel',
    'Date': 'Date',
    'Time In': 'Time In',
    'Time Out': 'Time Out',
    'No valid attendance data found in the file.': 'No valid attendance data found in the file.',
    'Successfully imported attendance records.': 'Successfully imported attendance records.',
    'Failed to import data.': 'Failed to import data.',
    'Error parsing file.': 'Error parsing file.',
    'Present': 'Present',
    'Abnormal': 'Abnormal',
    'Late': 'Late',
    'Search pages, apps, settings...': 'Search pages, apps, settings...',
    'Go to': 'Go to',
    'No results found for': 'No results found for',
    'Preferences': 'Preferences',
    'Customize your dashboard layout preferences.': 'Customize your dashboard layout preferences.',
    'Theme': 'Theme',
    'Typography': 'Typography',
    'Sidebar': 'Sidebar',
    'Header': 'Header',
    'Content Width': 'Content Width',
    'Color Preset': 'Color Preset',
    'Radius': 'Radius',
    "Here's what's happening with your business today.": "Here's what's happening with your business today.",
    'Good morning': 'Good morning',
    'Good afternoon': 'Good afternoon',
    'Good evening': 'Good evening',
    'User Management': 'User Management',
    'Manage all registered users from the database.': 'Manage all registered users from the database.',
    'Add User': 'Add User',
    'All Users': 'All Users',
    'Search users...': 'Search users...',
    'All Roles': 'All Roles',
    'No.': 'No.',
    'Role Type': 'Role Type',
    'Joined At': 'Joined At',
    'No users found.': 'No users found.',
    'Showing': 'Showing',
    'to': 'to',
    'of': 'of',
    'results': 'results',
    'Edit User': 'Edit User',
    'Add New User': 'Add New User',
    'Notification Email': 'Notification Email',
    'Avatar': 'Avatar',
    'Choose File': 'Choose File',
    'JPG, PNG, GIF up to 5MB': 'JPG, PNG, GIF up to 5MB',
    '(Leave empty to keep current)': '(Leave empty to keep current)',
    'Create User': 'Create User',
    'Delete User?': 'Delete User?',
    'Are you sure you want to delete': 'Are you sure you want to delete',
    'Yes, delete': 'Yes, delete',
    'User updated successfully!': 'User updated successfully!',
    'User created successfully!': 'User created successfully!',
    'User deleted successfully!': 'User deleted successfully!',
    'Avatar uploaded successfully!': 'Avatar uploaded successfully!',
    'Avatar upload failed!': 'Avatar upload failed!',
  },
  id: {
    // Navigation
    'Dashboard': 'Beranda',
    'Beranda': 'Beranda',
    'Akun Perkiraan': 'Akun Perkiraan',
    'Penjualan': 'Penjualan',
    'Penawaran Penjualan': 'Penawaran Penjualan',
    'Uang Muka Penjualan': 'Uang Muka Penjualan',
    'Faktur Penjualan': 'Faktur Penjualan',
    'Penerimaan Penjualan': 'Penerimaan Penjualan',
    'Pelanggan': 'Pelanggan',
    'Pembelian': 'Pembelian',
    'Pesanan Pembelian': 'Pesanan Pembelian',
    'Faktur Pembelian': 'Faktur Pembelian',
    'Uang Muka Pembelian': 'Uang Muka Pembelian',
    'Pembayaran Pembelian': 'Pembayaran Pembelian',
    'Pemasok': 'Pemasok',
    'Barang & Jasa': 'Barang & Jasa',
    'Buku Besar': 'Buku Besar',
    'Karyawan': 'Karyawan',
    'Analytics': 'Analitik',
    'Orders': 'Pesanan',
    'Products': 'Produk',
    'Customers': 'Pelanggan',
    'File Manager': 'Manajer File',
    'Chat': 'Obrolan',
    'Mail': 'Surat',
    'Kanban': 'Kanban',
    'Calendar': 'Kalender',
    'Project': 'Proyek',
    'Tasks': 'Tugas',
    'My Tasks': 'Tugas Saya',
    'AI Assistant': 'Asisten AI',
    'Layouts': 'Tata Letak',
    'Settings': 'Pengaturan',
    'Workspace': 'Ruang Kerja',
    'Apps': 'Aplikasi',
    'Search anything': 'Cari apa saja...',
    'Developer': 'Pengembang',
    'Setup Project': 'Siapkan Proyek',
    'Milestones': 'Pencapaian',
    'Module Flows': 'Alur Modul',
    'Administration': 'Administrasi',
    'Roles & Permissions': 'Peran & Izin',
    'Finance': 'Keuangan',
    'HR': 'SDM',
    // Settings page
    'Localization': 'Lokalisasi',
    'Manage your timezone and language preferences.': 'Kelola preferensi zona waktu dan bahasa Anda.',
    'Language': 'Bahasa',
    'Timezone': 'Zona Waktu',
    'Date Format': 'Format Tanggal',
    'Save preferences': 'Simpan preferensi',
    'Save changes': 'Simpan perubahan',
    'Preferences saved': 'Preferensi disimpan!',
    // Common UI
    'Loading': 'Memuat...',
    'Search': 'Cari',
    'Add': 'Tambah',
    'Edit': 'Ubah',
    'Delete': 'Hapus',
    'Cancel': 'Batal',
    'Confirm': 'Konfirmasi',
    'Export': 'Ekspor',
    'Import': 'Impor',
    'Status': 'Status',
    'Name': 'Nama',
    'Email': 'Email',
    'Role': 'Jabatan',
    'Department': 'Departemen',
    'Actions': 'Aksi',
    'Total': 'Total',
    'Date': 'Tanggal',
    'Description': 'Deskripsi',
    'Amount': 'Jumlah',
    'Period': 'Periode',
    'No data found': 'Tidak ada data.',
    'Paid': 'Lunas',
    'Pending': 'Menunggu',
    'Approve': 'Setujui',
    'Reject': 'Tolak',
    'approved': 'disetujui',
    'rejected': 'ditolak',
    'Leave Type': 'Jenis Cuti',
    'Duration': 'Durasi',
    'Reason': 'Alasan',
    'Candidate': 'Kandidat',
    'Role Applied': 'Posisi Dilamar',
    'Applied Date': 'Tanggal Melamar',
    'Rating': 'Penilaian',
    'View Profile': 'Lihat Profil',
    'Payroll generated successfully!': 'Penggajian berhasil dibuat!',
    'Payroll data exported successfully!': 'Data penggajian berhasil diekspor!',
    'Failed to export payroll data.': 'Gagal mengekspor data penggajian.',
    'Employee updated successfully!': 'Data karyawan berhasil diperbarui!',
    'Employee list is sourced from the Users database.': 'Daftar karyawan diambil dari database pengguna.',
    'View your organization\'s members. To add or remove users, use User Management.': 'Lihat anggota organisasi. Untuk tambah/hapus, gunakan Manajemen Pengguna.',
    'Manage employee leave requests and attendance records.': 'Kelola pengajuan cuti dan catatan kehadiran karyawan.',
    'View and manage employee salaries, allowances, and deductions.': 'Lihat dan kelola gaji, tunjangan, dan potongan karyawan.',
    'Applicant Tracking System to manage active job applications.': 'Sistem pelacakan pelamar untuk mengelola lamaran kerja aktif.',
    'Are you sure you want to update this leave request?': 'Apakah Anda yakin ingin mengubah status cuti ini?',
    // Dashboard
    'Welcome back': 'Selamat datang kembali',
    'Total Revenue': 'Total Pendapatan',
    'Active Users': 'Pengguna Aktif',
    'New Orders': 'Pesanan Baru',
    'Growth': 'Pertumbuhan',
    // HR
    'Employees': 'Karyawan',
    'Attendance': 'Kehadiran',
    'Payroll': 'Penggajian',
    'Recruitment': 'Rekrutmen',
    'HR Overview': 'Ikhtisar SDM',
    'Leave Requests': 'Pengajuan Cuti',
    'Total Employees': 'Total Karyawan',
    'Interviews': 'Wawancara',
    'Departments': 'Departemen',
    'Generate Payroll': 'Buat Penggajian',
    'Net Pay': 'Gaji Bersih',
    'Basic Salary': 'Gaji Pokok',
    'Allowance': 'Tunjangan',
    'Deduction': 'Potongan',
    'Finance Overview': 'Ikhtisar Keuangan',
    'Monitor your key financial metrics and recent activities.': 'Pantau metrik keuangan utama dan aktivitas terkini Anda.',
    'Total Revenue': 'Total Pendapatan',
    'Total Expenses': 'Total Pengeluaran',
    'Net Profit': 'Laba Bersih',
    'Outstanding Invoices': 'Faktur Belum Dibayar',
    'Cash & Bank': 'Kas & Bank',
    'Recent Transactions': 'Transaksi Terkini',
    'Reference': 'Referensi',
    'Type': 'Jenis',
    'Account': 'Akun',
    'Edit Employee': 'Edit Karyawan',
    'Add New Employee': 'Tambah Karyawan Baru',
    'Update employee details here.': 'Perbarui detail karyawan di sini.',
    'Enter the details of the new employee.': 'Masukkan detail karyawan baru.',
    'Select Employee': 'Pilih Karyawan',
    'Create a new payroll record for an employee.': 'Buat catatan penggajian baru untuk karyawan.',
    'A quick glance at human resources statistics and activities.': 'Gambaran singkat statistik dan aktivitas sumber daya manusia.',
    'Employee Distribution': 'Sebaran Karyawan',
    'Headcount by department': 'Jumlah per departemen',
    'Hiring Trends': 'Tren Rekrutmen',
    'New hires over the last 6 months': 'Karyawan baru dalam 6 bulan terakhir',
    'Recent Leave Requests': 'Pengajuan Cuti Terkini',
    'Upcoming Interviews': 'Wawancara Mendatang',
    'active': 'aktif',
    'pending approval': 'menunggu persetujuan',
    'Across the organization': 'Di seluruh organisasi',
    'upcoming sessions': 'sesi mendatang',
    'Record Income': 'Catat Pemasukan',
    'Add Expense': 'Tambah Pengeluaran',
    'Add Transaction': 'Tambah Transaksi',
    'Create Invoice': 'Buat Faktur',
    'Vendor': 'Vendor',
    'Category': 'Kategori',
    'Invoice No.': 'No. Faktur',
    'Customer': 'Pelanggan',
    'Due Date': 'Jatuh Tempo',
    'Income': 'Pemasukan',
    'Save': 'Simpan',
    'Add': 'Tambah',
    'New Data': 'Data Baru',
    'Filter': 'Filter',
    'From': 'Dari',
    'To': 's/d',
    'Date': 'Tanggal',
    'Description': 'Keterangan',
    'Total': 'Total',
    'Status': 'Status',
    'Action': 'Aksi',
    'Name': 'Nama',
    'Code': 'Kode',
    'Type': 'Jenis',
    'Unit': 'Satuan',
    'Customer': 'Pelanggan',
    'Supplier': 'Pemasok',
    'Number': 'Nomor',
    'Debit': 'Debit',
    'Credit': 'Kredit',
    'Ending Balance': 'Saldo Akhir',
    'Transaction Type': 'Tipe Transaksi',
    'Other Information': 'Informasi Lainnya',
    'Chart of Accounts': 'Akun Perkiraan',
    'General Ledger': 'Buku Besar',
    'Products & Services': 'Barang & Jasa',
    'Sales Quote': 'Penawaran Penjualan',
    'Sales Invoice': 'Faktur Penjualan',
    'Sales Down Payment': 'Uang Muka Penjualan',
    'Sales Receipt': 'Penerimaan Penjualan',
    'Purchase Order': 'Pesanan Pembelian',
    'Purchase Invoice': 'Faktur Pembelian',
    'Purchase Down Payment': 'Uang Muka Pembelian',
    'Purchase Payment': 'Pembayaran Pembelian',
    'Brand': 'Merek',
    'Income & Expenses': 'Pemasukan & Pengeluaran',
    'Total Balance': 'Total Saldo',
    'Unpaid Invoices': 'Invoice Belum Dibayar',
    'Total Transactions': 'Total Transaksi',
    'Unpaid': 'Belum Dibayar',
    'Expense': 'Pengeluaran',
    'Transfer': 'Transfer',
    'Transactions': 'Transaksi',
    'Invoices': 'Faktur',
    'Expenses': 'Pengeluaran',
    'Accounts': 'Akun',
    'Income': 'Pemasukan',
    'Balance': 'Saldo',
    'All Categories': 'Semua Kategori',
    'Delete Expense': 'Hapus Pengeluaran',
    'Delete Transaction': 'Hapus Transaksi',
    'Delete Invoice': 'Hapus Faktur',
    'Are you sure you want to delete this expense record? This action cannot be undone.': 'Apakah Anda yakin ingin menghapus catatan ini? Tindakan ini tidak dapat dibatalkan.',
    'Are you sure you want to delete this record? This action cannot be undone.': 'Apakah Anda yakin ingin menghapus catatan ini? Tindakan ini tidak dapat dibatalkan.',
    'Track and analyze your company spending.': 'Lacak dan analisis pengeluaran perusahaan Anda.',
    'Track and manage your company invoices.': 'Lacak dan kelola faktur perusahaan Anda.',
    'Manage your bank and cash accounts.': 'Kelola akun bank dan kas Anda.',
    'Export': 'Ekspor',
    'Last 30 days': '30 hari terakhir',
    'Last 7 days': '7 hari terakhir',
    'This year': 'Tahun ini',
    'vs. last month': 'vs. bulan lalu',
    'Avg. order value': 'Rata-rata nilai pesanan',
    'Conversion rate': 'Tingkat konversi',
    'Revenue overview': 'Ringkasan pendapatan',
    'Monthly revenue performance': 'Performa pendapatan bulanan',
    'Traffic sources': 'Sumber lalu lintas',
    'Where your visitors come from': 'Dari mana pengunjung Anda berasal',
    'Direct': 'Langsung',
    'Organic search': 'Pencarian organik',
    'Social media': 'Media sosial',
    'Other': 'Lainnya',
    'Recent activity': 'Aktivitas terkini',
    'View all': 'Lihat semua',
    'Monthly goals': 'Target bulanan',
    'Keep the momentum going': 'Pertahankan momentum',
    'Revenue target': 'Target pendapatan',
    'New customers': 'Pelanggan baru',
    'Orders fulfilled': 'Pesanan dipenuhi',
    'Top products': 'Produk teratas',
    'Recent orders': 'Pesanan terbaru',
    'Your latest transactions': 'Transaksi terbaru Anda',
    'Order': 'Pesanan',
    'Date': 'Tanggal',
    'Amount': 'Jumlah',
    'Status': 'Status',
    'Analytics overview': 'Ringkasan analitik',
    'A clear view of the signals shaping your business this month.': 'Pandangan jelas tentang sinyal yang membentuk bisnis Anda bulan ini.',
    'Export report': 'Ekspor laporan',
    'Unique visitors': 'Pengunjung unik',
    'Page views': 'Tayangan halaman',
    'vs last month': 'vs bulan lalu',
    'Acquisition performance': 'Performa akuisisi',
    'Visitors and conversions over the selected period': 'Pengunjung dan konversi selama periode yang dipilih',
    'Visitors': 'Pengunjung',
    'Conversions': 'Konversi',
    'Share of total visitors': 'Bagian dari total pengunjung',
    'total visitors': 'total pengunjung',
    'Conversion funnel': 'Corong konversi',
    'How visitors move through your store': 'Bagaimana pengunjung bergerak melalui toko Anda',
    'Details': 'Detail',
    'Visited site': 'Mengunjungi situs',
    'Viewed product': 'Melihat produk',
    'Added to cart': 'Ditambahkan ke keranjang',
    'Completed checkout': 'Penyelesaian pembayaran',
    'Top pages': 'Halaman teratas',
    'Most visited this month': 'Paling banyak dikunjungi bulan ini',
    'Revenue by channel': 'Pendapatan berdasarkan saluran',
    'Attributed revenue for the last 30 days': 'Pendapatan yang dikaitkan selama 30 hari terakhir',
    'Referral': 'Rujukan',
    'Workspace details and timezone': 'Detail ruang kerja dan zona waktu',
    'Profile and login credentials': 'Profil dan kredensial masuk',
    'Theme and UI preferences': 'Tema dan preferensi UI',
    'Email and push alerts': 'Peringatan email dan dorongan',
    '2FA and active sessions': '2FA dan sesi aktif',
    'Payment methods and plans': 'Metode pembayaran dan paket',
    'Workspace Profile': 'Profil Ruang Kerja',
    "This is your company's presence on HaiMotion.": "Ini adalah kehadiran perusahaan Anda di HaiMotion.",
    'Workspace Logo': 'Logo Ruang Kerja',
    'JPG, GIF or PNG. Max size 2MB.': 'JPG, GIF atau PNG. Ukuran maks 2MB.',
    'Workspace Name': 'Nama Ruang Kerja',
    'Workspace URL': 'URL Ruang Kerja',
    'Save changes': 'Simpan perubahan',
    'Preferences saved': 'Preferensi disimpan',
    'Theme Preferences': 'Preferensi Tema',
    'Customize the look and feel of your dashboard.': 'Sesuaikan tampilan dan nuansa dasbor Anda.',
    'Interface Theme': 'Tema Antarmuka',
    'Light': 'Terang',
    'Dark': 'Gelap',
    'System': 'Sistem',
    'Accent Color': 'Warna Aksen',
    'Security Settings': 'Pengaturan Keamanan',
    'Manage your authentication methods and passkeys.': 'Kelola metode autentikasi dan kunci pas Anda.',
    'Passkeys (WebAuthn)': 'Kunci Pas (WebAuthn)',
    'Please enter a device name.': 'Silakan masukkan nama perangkat.',
    'Failed to add passkey': 'Gagal menambahkan kunci pas',
    'Network error or cancelled.': 'Kesalahan jaringan atau dibatalkan.',
    'Loading passkeys...': 'Memuat kunci pas...',
    'No passkeys registered yet.': 'Belum ada kunci pas yang terdaftar.',
    'Unknown Device': 'Perangkat Tidak Dikenal',
    'Added: ': 'Ditambahkan: ',
    'Unknown': 'Tidak dikenal',
    'Add New Passkey (e.g. My MacBook)': 'Tambah Kunci Pas Baru (misal MacBook Saya)',
    'Device Name': 'Nama Perangkat',
    'Add Passkey': 'Tambah Kunci Pas',
    'Adding...': 'Menambahkan...',
    'Profile saved successfully!': 'Profil berhasil disimpan!',
    'Passwords do not match!': 'Kata sandi tidak cocok!',
    'Basic Information': 'Informasi Dasar',
    'Your name, staff code, and a short bio.': 'Nama, kode staf, dan biodata singkat.',
    'Position / Title': 'Posisi / Jabatan',
    'Managed by admin': 'Dikelola oleh admin',
    'Staff Code': 'Kode Staf',
    'Bio': 'Biodata',
    'Tell us a little about yourself...': 'Ceritakan sedikit tentang diri Anda...',
    'Account & Security': 'Akun & Keamanan',
    'Role, login email, and account password.': 'Peran, email login, dan kata sandi akun.',
    'User Role': 'Peran Pengguna',
    'Role is managed by admin': 'Peran dikelola oleh admin',
    'Email Login': 'Email Login',
    'Optional — for Gmail notifications': 'Opsional — untuk notifikasi Gmail',
    "Leave blank if you don't want to change your password": "Biarkan kosong jika Anda tidak ingin mengubah kata sandi",
    'Confirm Password': 'Konfirmasi Kata Sandi',
    'Passwords do not match': 'Kata sandi tidak cocok',
    'Passwords match': 'Kata sandi cocok',
    'Profile Picture': 'Foto Profil',
    'Upload and adjust your avatar photo.': 'Unggah dan sesuaikan foto avatar Anda.',
    'Uploading...': 'Mengunggah...',
    'Upload new photo': 'Unggah foto baru',
    'Remove': 'Hapus',
    'JPG, GIF or PNG. Max 5MB. Hover the photo to upload directly.': 'JPG, GIF atau PNG. Maks 5MB. Arahkan kursor ke foto untuk mengunggah langsung.',
    'Fields marked with': 'Bidang yang ditandai dengan',
    'are required.': 'wajib diisi.',
    'Saving...': 'Menyimpan...',
    'Save Changes': 'Simpan Perubahan',
    'Daily Attendance': 'Kehadiran Harian',
    'Import Excel': 'Impor Excel',
    'Date': 'Tanggal',
    'Time In': 'Jam Masuk',
    'Time Out': 'Jam Keluar',
    'No valid attendance data found in the file.': 'Tidak ada data kehadiran yang valid di file ini.',
    'Successfully imported attendance records.': 'Berhasil mengimpor catatan kehadiran.',
    'Failed to import data.': 'Gagal mengimpor data.',
    'Error parsing file.': 'Terjadi kesalahan saat membaca file.',
    'Present': 'Hadir',
    'Abnormal': 'Tidak Normal',
    'Late': 'Terlambat',
    'Search pages, apps, settings...': 'Cari halaman, aplikasi, pengaturan...',
    'Go to': 'Ke',
    'No results found for': 'Tidak ada hasil untuk',
    'Preferences': 'Preferensi',
    'Customize your dashboard layout preferences.': 'Sesuaikan preferensi tata letak dasbor Anda.',
    'Theme': 'Tema',
    'Typography': 'Tipografi',
    'Sidebar': 'Bilah Samping',
    'Header': 'Tajuk',
    'Content Width': 'Lebar Konten',
    'Color Preset': 'Prasetel Warna',
    'Radius': 'Radius',
    "Here's what's happening with your business today.": "Inilah yang terjadi dengan bisnis Anda hari ini.",
    'Good morning': 'Selamat pagi',
    'Good afternoon': 'Selamat siang',
    'Good evening': 'Selamat malam',
    'User Management': 'Manajemen Pengguna',
    'Manage all registered users from the database.': 'Kelola semua pengguna terdaftar dari basis data.',
    'Add User': 'Tambah Pengguna',
    'All Users': 'Semua Pengguna',
    'Search users...': 'Cari pengguna...',
    'All Roles': 'Semua Peran',
    'No.': 'No.',
    'Role Type': 'Tipe Peran',
    'Joined At': 'Bergabung Pada',
    'No users found.': 'Tidak ada pengguna ditemukan.',
    'Showing': 'Menampilkan',
    'to': 'hingga',
    'of': 'dari',
    'results': 'hasil',
    'Edit User': 'Ubah Pengguna',
    'Add New User': 'Tambah Pengguna Baru',
    'Notification Email': 'Email Notifikasi',
    'Avatar': 'Avatar',
    'Choose File': 'Pilih Berkas',
    'JPG, PNG, GIF up to 5MB': 'JPG, PNG, GIF hingga 5MB',
    '(Leave empty to keep current)': '(Biarkan kosong untuk mempertahankan yang ada)',
    'Create User': 'Buat Pengguna',
    'Delete User?': 'Hapus Pengguna?',
    'Are you sure you want to delete': 'Apakah Anda yakin ingin menghapus',
    'Yes, delete': 'Ya, hapus',
    'User updated successfully!': 'Pengguna berhasil diperbarui!',
    'User created successfully!': 'Pengguna berhasil dibuat!',
    'User deleted successfully!': 'Pengguna berhasil dihapus!',
    'Avatar uploaded successfully!': 'Avatar berhasil diunggah!',
    'Avatar upload failed!': 'Unggah avatar gagal!',
  }
}

export const TIMEZONES = [
  { label: 'Western Indonesia Time (WIB) — UTC+7', value: 'Asia/Jakarta' },
  { label: 'Central Indonesia Time (WITA) — UTC+8', value: 'Asia/Makassar' },
  { label: 'Eastern Indonesia Time (WIT) — UTC+9', value: 'Asia/Jayapura' },
  { label: 'Singapore Time (SGT) — UTC+8', value: 'Asia/Singapore' },
  { label: 'Greenwich Mean Time (GMT) — UTC+0', value: 'Europe/London' },
  { label: 'Central European Time (CET) — UTC+1', value: 'Europe/Paris' },
  { label: 'Eastern Time (ET) — UTC-5', value: 'America/New_York' },
  { label: 'Pacific Time (PT) — UTC-8', value: 'America/Los_Angeles' },
  { label: 'Japan Standard Time (JST) — UTC+9', value: 'Asia/Tokyo' },
  { label: 'India Standard Time (IST) — UTC+5:30', value: 'Asia/Kolkata' },
  { label: 'Australia Eastern Time (AET) — UTC+10', value: 'Australia/Sydney' },
]

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  timezone: string
  setTimezone: (tz: string) => void
  t: (key: string) => string
  formatDate: (date: Date | string) => string
  formatTime: (date: Date | string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const LANG_KEY = 'haimotion_language'
const TZ_KEY = 'haimotion_timezone'

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')
  const [timezone, setTimezoneState] = useState<string>('Asia/Jakarta')

  // Hydrate from localStorage on mount
  useEffect(() => {
    const savedLang = localStorage.getItem(LANG_KEY) as Language | null
    const savedTz = localStorage.getItem(TZ_KEY)
    if (savedLang && (savedLang === 'en' || savedLang === 'id')) {
      setLanguageState(savedLang)
    }
    if (savedTz) {
      setTimezoneState(savedTz)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem(LANG_KEY, lang)
  }

  const setTimezone = (tz: string) => {
    setTimezoneState(tz)
    localStorage.setItem(TZ_KEY, tz)
  }

  const t = (key: string) => {
    return dictionaries[language][key] ?? key
  }

  const formatDate = (date: Date | string) => {
    const d = typeof date === 'string' ? new Date(date) : date
    return new Intl.DateTimeFormat(language === 'id' ? 'id-ID' : 'en-US', {
      timeZone: timezone,
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    }).format(d)
  }

  const formatTime = (date: Date | string) => {
    const d = typeof date === 'string' ? new Date(date) : date
    return new Intl.DateTimeFormat(language === 'id' ? 'id-ID' : 'en-US', {
      timeZone: timezone,
      hour: '2-digit',
      minute: '2-digit',
    }).format(d)
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, timezone, setTimezone, t, formatDate, formatTime }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
