'use client'

import { Activity, ArrowDownRight, ArrowUpRight, BarChart3, CalendarDays, CheckCircle2, CircleCheck, Clock3, Mail, MessageCircle, Package, ShoppingCart, Users } from 'lucide-react'

const pageContent: Record<string, { icon: typeof Activity; eyebrow: string; title: string; description: string; stats: [string, string, string, 'up' | 'down'][]; rows: [string, string, string][] }> = {
  Analytics: { icon: BarChart3, eyebrow: 'Workspace / Analytics', title: 'Analytics', description: 'Understand what is driving your business forward.', stats: [['Visitors', '24.8k', '+16.4%', 'up'], ['Conversion rate', '4.82%', '+0.8%', 'up'], ['Revenue per visitor', '$11.49', '+4.2%', 'up']], rows: [['Direct traffic', '10,416 visitors', '42%'], ['Organic search', '6,696 visitors', '27%'], ['Social media', '3,720 visitors', '15%'], ['Referral', '3,968 visitors', '16%']] },
  Orders: { icon: ShoppingCart, eyebrow: 'Workspace / Orders', title: 'Orders', description: 'Track every purchase from checkout to fulfillment.', stats: [['Open orders', '184', '+12 today', 'up'], ['Fulfilled', '1,245', '87.1% total', 'up'], ['Refunds', '18', '-4.2% this month', 'down']], rows: [['#N-28391', 'Olivia Martin', '$248.00'], ['#N-28390', 'Liam Chen', '$1,240.00'], ['#N-28389', 'Ava Williams', '$86.00'], ['#N-28388', 'Noah Smith', '$420.00']] },
  Products: { icon: Package, eyebrow: 'Workspace / Products', title: 'Products', description: 'Manage your catalog, inventory, and product performance.', stats: [['Active products', '248', '+18 this month', 'up'], ['Low stock', '12', 'Needs attention', 'down'], ['Catalog value', '$482k', '+8.6% this month', 'up']], rows: [['Aurora Headphones', '1,240 sold', '$124,820'], ['Nimbus Keyboard', '864 sold', '$86,400'], ['Orbit Desk Lamp', '622 sold', '$41,780'], ['Atlas Backpack', '412 sold', '$29,664']] },
  Customers: { icon: Users, eyebrow: 'Workspace / Customers', title: 'Customers', description: 'Build better relationships with every customer.', stats: [['Total customers', '8,429', '+12.5%', 'up'], ['Returning rate', '38.4%', '+3.8%', 'up'], ['Avg. lifetime value', '$684', '+6.1%', 'up']], rows: [['Olivia Martin', 'Returning customer', '$2,840 lifetime'], ['Liam Chen', 'New this month', '$1,240 lifetime'], ['Ava Williams', 'Returning customer', '$986 lifetime'], ['Noah Smith', 'At risk', '$420 lifetime']] },
  Chat: { icon: MessageCircle, eyebrow: 'Apps / Chat', title: 'Chat', description: 'Keep your team conversations in one focused workspace.', stats: [['Unread messages', '4', 'Across 2 channels', 'up'], ['Active members', '18', 'Online now', 'up'], ['Open threads', '12', '+3 today', 'up']], rows: [['Product launch', 'Maya, Jordan, Alex', 'Active now'], ['Q3 campaign', '6 participants', '12 min ago'], ['Support handoff', 'You and Olivia', '34 min ago'], ['Design review', '4 participants', '1 hr ago']] },
  Mail: { icon: Mail, eyebrow: 'Apps / Mail', title: 'Mail', description: 'Stay on top of important customer and team correspondence.', stats: [['Inbox', '24', '8 need a reply', 'down'], ['Sent this week', '186', '+21.4%', 'up'], ['Response time', '2h 18m', '-12 minutes', 'up']], rows: [['Q3 partnership proposal', 'Maya Chen', 'Needs reply'], ['Invoice #N-28391', 'HaiMotion Billing', 'Today'], ['Product feedback', 'Ava Williams', 'Yesterday'], ['Welcome to HaiMotion', 'Automated', 'Sent']] },
  Kanban: { icon: CheckCircle2, eyebrow: 'Apps / Kanban', title: 'Kanban', description: 'Move projects forward with a clear view of every task.', stats: [['To do', '24', '5 due today', 'down'], ['In progress', '12', '3 blocked', 'down'], ['Completed', '86', '+14 this week', 'up']], rows: [['Prepare launch assets', 'Marketing', 'In progress'], ['Review Q3 numbers', 'Finance', 'To do'], ['Publish customer story', 'Content', 'In progress'], ['Archive old campaigns', 'Operations', 'Completed']] },
  Calendar: { icon: CalendarDays, eyebrow: 'Apps / Calendar', title: 'Calendar', description: 'Plan your time and keep the team aligned.', stats: [['Today', '4', 'Next in 32 minutes', 'up'], ['This week', '18', '6 shared events', 'up'], ['Focus time', '6h 30m', '+42 minutes', 'up']], rows: [['Daily standup', 'Today · 09:30', 'Team'], ['Product sync', 'Today · 11:00', 'Product'], ['Customer review', 'Tomorrow · 14:00', 'Sales'], ['Q3 planning', 'Fri · 10:00', 'Leadership']] },
  Settings: { icon: Activity, eyebrow: 'Workspace / Settings', title: 'Settings', description: 'Configure your workspace and personal preferences.', stats: [['Workspace members', '24', '3 pending invites', 'up'], ['Integrations', '8', 'All connected', 'up'], ['Security score', 'Good', 'No action needed', 'up']], rows: [['Workspace profile', 'HaiMotion HQ', 'Configured'], ['Notifications', 'Email and desktop', 'Configured'], ['Billing plan', 'Growth · $79/mo', 'Active'], ['Security', '2FA enforced', 'Protected']] },
}

export function SectionPage({ section }: { section: string }) {
  const content = pageContent[section] ?? pageContent.Analytics
  const Icon = content.icon
  return <div className="flex flex-col gap-7"><div className="flex flex-col gap-3"><div className="flex items-center gap-2 text-xs text-muted-foreground"><Icon className="size-4 text-primary" /><span>{content.eyebrow}</span></div><h1 className="text-3xl font-semibold tracking-tight">{content.title}</h1><p className="max-w-xl text-sm leading-6 text-muted-foreground">{content.description}</p></div><div className="grid gap-4 md:grid-cols-3">{content.stats.map(([label, value, detail, trend]) => <div key={label} className="rounded-xl border border-border bg-card p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-4 text-2xl font-semibold tracking-tight">{value}</p><p className={`mt-2 flex items-center gap-1 text-xs ${trend === 'down' ? 'text-muted-foreground' : 'text-primary'}`}>{trend === 'down' ? <ArrowDownRight className="size-3" /> : <ArrowUpRight className="size-3" />}{detail}</p></div>)}</div><div className="grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><section className="rounded-xl border border-border bg-card"><div className="flex items-center justify-between border-b border-border p-5"><div><h2 className="font-semibold">{section === 'Analytics' ? 'Traffic performance' : `${content.title} overview`}</h2><p className="mt-1 text-xs text-muted-foreground">Updated moments ago</p></div><button className="rounded-lg border border-border px-3 py-2 text-xs font-medium hover:bg-muted">Export</button></div><div className="flex flex-col">{content.rows.map(([name, meta, value]) => <div key={name} className="flex items-center gap-4 border-b border-border px-5 py-4 last:border-0"><div className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-muted"><Icon className="size-4 text-primary" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{name}</p><p className="mt-1 truncate text-xs text-muted-foreground">{meta}</p></div><span className="text-xs font-medium text-muted-foreground">{value}</span></div>)}</div></section><aside className="rounded-xl border border-border bg-card p-5"><div className="flex items-center gap-2"><CircleCheck className="size-4 text-primary" /><h2 className="font-semibold">Quick actions</h2></div><div className="mt-5 flex flex-col gap-3">{['View full report', 'Create new item', 'Invite teammate', 'Open documentation'].map((action) => <button key={action} className="flex items-center justify-between rounded-lg border border-border px-4 py-3 text-left text-sm hover:bg-muted"><span>{action}</span><Clock3 className="size-4 text-muted-foreground" /></button>)}</div></aside></div></div>
}

export default SectionPage
